FROM debian:11

RUN apt-get update && apt-get install -y cmake make g++ libxerces-c-dev libxml2 libxml2-dev libasio-dev unzip

WORKDIR /usr/src/app

COPY CMakeLists.txt .
COPY src/ src/
COPY models/ models/
COPY lib/ lib/

RUN mkdir build && cd build && cmake -DMODE=Master .. && make

CMD ["/bin/sh"]